variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "us-east-1"
}

variable "aws_profile" {
  description = "AWS CLI profile"
  type        = string
  default     = "rchsandbox"
}

variable "ami_id" {
  description = "AMI ID for EC2 instance generated by packer"
  type        = string
  default     = "ami-018c64ef5b523f5ed"
}

variable "instance_type" {
  description = "EC2 instance type"
  type        = string
  default     = "t2.micro"
}

variable "key_name" {
  description = "EC2 key pair name"
  type        = string
  default     = "strinh"
}

variable "subnet_id" {
  description = "Subnet ID for EC2 instance"
  type        = string
  default     = "subnet-074002489fcb3cf3b"
}

variable "user_data_file" {
  description = "Path to user data script"
  type        = string
  default     = "setup.sh"
}

variable "hf_token" {
  description = "HuggingFace API Token"
  type        = string
  sensitive   = true
}

variable "duckdns_domain" {
  description = "DuckDNS subdomain"
  type        = string
  default     = "ado-chat.duckdns.org"
}

variable "duckdns_token" {
  description = "DuckDNS token for dynamic DNS updates"
  type        = string
  sensitive   = true
}

variable "letsencrypt_email" {
  description = "Email for Let's Encrypt certificate notifications"
  type        = string
}
